import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./shared/Navbar";
import Footer from "./shared/Footer";
import { ContextProvider } from "./Context/Context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Devs Blogers",
  description:
    "Hey there , this is  Developers Blogs web appplication Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className} data-theme='light'>
        <ContextProvider>
          <Navbar />
          <div className=''>{children}</div>
          <Footer />
        </ContextProvider>
      </body>
    </html>
  );
}
